import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import './editor.css';

type Entity = { id: string; name: string; type: string; visible?: boolean; transform?: { x?: number; y?: number; rotation?: number; scale?: number }; components?: string[] };
type Scene = { id: string; name: string; entities: Entity[]; modified?: string };
type Asset = { id?: string; name: string; type?: string; typeLabel?: string; kind?: string; path?: string; size?: number };
type Project = { id: string; name: string; template?: string; scenes: Scene[]; assets: Asset[] };

declare global {
  interface Window { TomCatStore?: any; TomCatBridge?: any; TomCatStorage?: any; TomCatPlatformStorage?: any; Module?: any; }
}

const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value));
const fallbackScene = (): Scene => ({ id: 'MainScene', name: 'MainScene', entities: [
  { id: uid('camera'), name: 'Main Camera', type: 'Camera', visible: true, transform: { x: 0, y: 0, rotation: 0, scale: 1 }, components: ['Transform', 'Camera'] },
  { id: uid('ground'), name: 'Ground', type: 'Sprite', visible: true, transform: { x: 0, y: -2, rotation: 0, scale: 8 }, components: ['Transform', 'SpriteRenderer'] },
  { id: uid('player'), name: 'Player', type: 'Sprite', visible: true, transform: { x: 0, y: 0, rotation: 0, scale: .5 }, components: ['Transform', 'SpriteRenderer'] },
] });
const fallbackProject = (): Project => ({ id: uid('project'), name: 'Untitled Project', template: '2D 空项目', scenes: [fallbackScene()], assets: [] });
const bridgeSend = (type: string, payload?: unknown) => { try { window.TomCatBridge?.send(type, payload); } catch { /* optional bridge */ } };

function readProject(): Project {
  const store = window.TomCatStore;
  const params = new URLSearchParams(location.search);
  const requested = params.get('project') || localStorage.getItem('tomcat.lastProjectId') || '';
  let project = store && (store.get(requested) || store.list?.()[0]);
  if (!project) project = store?.create?.({ name: 'Untitled Project', template: '2D 空项目' }) || fallbackProject();
  return project as Project;
}

export default function EditorApp() {
  const [project, setProject] = useState<Project>(() => readProject());
  const params = useMemo(() => new URLSearchParams(location.search), []);
  const [sceneId, setSceneId] = useState(params.get('scene') || project.scenes[0]?.id);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [tool, setTool] = useState('select');
  const [viewport, setViewport] = useState<'scene' | 'game'>('scene');
  const [running, setRunning] = useState(false);
  const [paused, setPaused] = useState(false);
  const [grid, setGrid] = useState(true);
  const [dirty, setDirty] = useState(false);
  const [frame, setFrame] = useState(0);
  const [query, setQuery] = useState('');
  const [toasts, setToasts] = useState<{ id: string; text: string; error?: boolean }[]>([]);
  const [entityModal, setEntityModal] = useState(false);
  const [sceneModal, setSceneModal] = useState<'create' | 'rename' | null>(null);
  const [deleteScene, setDeleteScene] = useState(false);
  const [entityName, setEntityName] = useState('');
  const [entityType, setEntityType] = useState('Sprite');
  const [sceneName, setSceneName] = useState('');
  const picker = useRef<HTMLInputElement>(null);
  const scene = (project.scenes.find((s) => s.id === sceneId) || project.scenes[0]) as Scene;
  const activeEntities = running ? (scene.entities.map((e) => clone(e))) : scene.entities;
  const selected = activeEntities.find((e) => e.id === selectedId);
  const notify = useCallback((text: string, error = false) => { const id = uid('toast'); setToasts((v) => [...v, { id, text, error }]); setTimeout(() => setToasts((v) => v.filter((t) => t.id !== id)), 3500); }, []);
  const updateScene = useCallback((mutate: (s: Scene) => Scene) => setProject((p) => ({ ...p, scenes: p.scenes.map((s) => s.id === scene.id ? mutate(clone(s)) : s) })), [scene?.id]);
  const markDirty = () => setDirty(true);

  useEffect(() => { localStorage.setItem('tomcat.lastProjectId', project.id); localStorage.setItem('tomcat.lastProject', project.name); }, [project]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's') { event.preventDefault(); saveScene(); } if (event.key === 'F6') { event.preventDefault(); toggleRun(); } if (['q', 'w', 'e', 'r'].includes(event.key.toLowerCase()) && !(event.target as HTMLElement)?.matches?.('input,textarea,select')) setTool(({ q: 'select', w: 'translate', e: 'rotate', r: 'scale' } as any)[event.key.toLowerCase()]); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); });
  function saveScene() { if (running) stopRun(); const saved = window.TomCatStore?.saveScene?.(project.id, { ...scene, modified: new Date().toISOString() }); if (saved) setProject(saved); setDirty(false); bridgeSend('scene.save', { projectId: project.id, sceneId: scene.id }); notify(`场景 ${scene.name} 已保存`); }
  function addEntity() { const entity: Entity = { id: window.TomCatStore?.uid?.('entity') || uid('entity'), name: entityName.trim() || 'Entity', type: entityType, visible: true, transform: { x: 0, y: 0, rotation: 0, scale: 1 }, components: entityType === 'Camera' ? ['Transform', 'Camera'] : entityType === 'Sprite' ? ['Transform', 'SpriteRenderer'] : ['Transform'] }; updateScene((s) => ({ ...s, entities: [...s.entities, entity] })); setSelectedId(entity.id); setEntityModal(false); setEntityName(''); markDirty(); bridgeSend('scene.entity.create', { projectId: project.id, sceneId: scene.id, entity }); notify(`已添加实体：${entity.name}`); }
  function deleteEntity() { if (!selected || running) return; updateScene((s) => ({ ...s, entities: s.entities.filter((e) => e.id !== selected.id) })); setSelectedId(null); markDirty(); notify(`已删除实体：${selected.name}`); }
  function duplicateEntity() { if (!selected || running) return; const copy = clone(selected); copy.id = uid('entity'); copy.name = `${copy.name} Copy`; copy.transform = { ...copy.transform, x: Number(copy.transform?.x || 0) + .5 }; updateScene((s) => ({ ...s, entities: [...s.entities, copy] })); setSelectedId(copy.id); markDirty(); }
  function toggleRun() { if (running) return stopRun(); if (dirty) saveScene(); setRunning(true); setPaused(false); setFrame(0); setViewport('game'); bridgeSend('runtime.play', { projectId: project.id, sceneId: scene.id }); notify('运行时已启动'); }
  function stopRun() { setRunning(false); setPaused(false); setFrame(0); setViewport('scene'); bridgeSend('runtime.stop', { projectId: project.id, sceneId: scene.id }); }
  function togglePause() { if (!running) return toggleRun(); setPaused((v) => !v); bridgeSend(paused ? 'runtime.resume' : 'runtime.pause', { projectId: project.id }); }
  function stepRun() { if (!running) toggleRun(); setPaused(true); setFrame((v) => v + 1); bridgeSend('runtime.step', { frame: frame + 1 }); }
  function updateSelected(patch: Partial<Entity>, transform?: Partial<NonNullable<Entity['transform']>>) { if (!selected || running) return; updateScene((s) => ({ ...s, entities: s.entities.map((e) => e.id === selected.id ? { ...e, ...patch, transform: transform ? { ...e.transform, ...transform } : e.transform } : e) })); markDirty(); }
  function createScene() { const name = sceneName.trim() || 'New Scene'; if (project.scenes.some((s) => s.name.toLowerCase() === name.toLowerCase())) return notify('场景名称已存在', true); const created = { id: window.TomCatStore?.uid?.('scene') || uid('scene'), name, entities: [] }; setProject((p) => ({ ...p, scenes: [...p.scenes, created] })); setSceneId(created.id); setSelectedId(null); setSceneModal(null); markDirty(); notify(`已创建场景：${name}`); }
  function renameScene() { const name = sceneName.trim(); if (!name) return; updateScene((s) => ({ ...s, name, modified: new Date().toISOString() })); setSceneModal(null); markDirty(); }
  function removeScene() { if (project.scenes.length <= 1) return notify('项目至少需要保留一个场景', true); const next = project.scenes.filter((s) => s.id !== scene.id); setProject((p) => ({ ...p, scenes: next })); setSceneId(next[0].id); setSelectedId(null); setDeleteScene(false); notify('场景已删除'); }
  function importAssets(files: FileList | null) { if (!files) return; const list = [...files]; const store = window.TomCatStore; list.forEach((file) => store?.addAsset?.(project.id, { name: file.name, size: file.size, typeLabel: store.typeFor?.(file.name), kind: store.kindFor?.(file.name), path: `Assets/${file.name}` })); setProject(store?.get?.(project.id) || { ...project, assets: [...project.assets, ...list.map((f) => ({ name: f.name, size: f.size, kind: 'file', type: f.type }))] }); notify(`已导入 ${list.length} 个资源`); bridgeSend('asset.import', { projectId: project.id }); }
  const glyph: Record<string, string> = { Camera: '⌾', Sprite: '◇', Light: '☼', Empty: '○' };
  const icon: Record<string, string> = { scene: '▣', texture: '▧', script: '▤', audio: '♫', file: '□' };
  const filteredAssets = project.assets.filter((a) => `${a.name} ${a.type || a.typeLabel || ''}`.toLowerCase().includes(query.toLowerCase()));

  return <div className="editor-shell">
    <header className="editor-menu"><a className="brand" href="../hub/"><span className="brand-mark">TC</span><span>TomCat</span></a><div className="menu-links">{['文件', '编辑', '视图', '帮助'].map((m) => <button key={m} onClick={() => notify(`${m}菜单可用`)}>{m}</button>)}</div><span className="tool-divider" /><strong>{project.name}</strong><span className="muted">/</span><span className="muted">{scene.name}</span><span className="spacer" /><span className={`save-indicator ${dirty ? '' : 'ready'}`}>● {dirty ? '有未保存修改' : '已保存'}</span><span className="badge">REACT</span><button onClick={saveScene}>保存</button><button className="primary" onClick={toggleRun}>{running ? '■ 停止' : '▶ 运行'}</button><button onClick={() => window.open(`../runtime/?project=${encodeURIComponent(project.id)}&scene=${encodeURIComponent(scene.id)}`, '_blank')}>↗</button></header>
    <div className="editor-tools"><>{[['select', '↖'], ['translate', '✣'], ['rotate', '◌'], ['scale', '⌗']].map(([id, label]) => <button key={id} className={`tool-button ${tool === id ? 'active' : ''}`} onClick={() => setTool(id)}>{label}</button>)}</><span className="tool-divider" /><button className="tool-button" onClick={() => selected && notify(`已聚焦：${selected.name}`)}>⌖</button><button className={`tool-button ${grid ? 'active' : ''}`} onClick={() => setGrid((v) => !v)}>▦</button><span className="tool-divider" /><label className="muted">场景</label><select value={scene.id} onChange={(e) => { if (dirty) saveScene(); setSceneId(e.target.value); setSelectedId(null); }}><>{project.scenes.map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</></select><button className="tool-button" onClick={() => { setSceneName(''); setSceneModal('create'); }}>＋</button><button className="tool-button" onClick={() => { setSceneName(scene.name); setSceneModal('rename'); }}>✎</button><button className="tool-button" onClick={() => setDeleteScene(true)}>×</button><span className="spacer" /><span className="muted">1280 × 720</span></div>
    <aside className="editor-pane"><div className="pane-heading"><span>Scene Hierarchy</span><button onClick={() => setEntityModal(true)}>＋</button></div><button className={`scene-tree-row ${!selectedId ? 'selected' : ''}`} onClick={() => setSelectedId(null)}><span>▾</span><span className="entity-glyph">▣</span><span className="entity-name">{scene.name}</span></button><div className="scene-tree-child">{scene.entities.length ? scene.entities.map((e) => <button className={`scene-tree-row ${e.id === selectedId ? 'selected' : ''}`} key={e.id} onClick={() => setSelectedId(e.id)}><span>·</span><span className="entity-glyph">{glyph[e.type] || '○'}</span><span className="entity-name">{e.name}</span><span className="visibility" onClick={(event) => { event.stopPropagation(); updateScene((s) => ({ ...s, entities: s.entities.map((x) => x.id === e.id ? { ...x, visible: x.visible === false } : x) })); markDirty(); }}>{e.visible === false ? '⊘' : '◉'}</span></button>) : <div className="empty small">场景中暂无实体</div>}</div><div className="pane-heading"><span>Bridge capabilities</span></div><div className="capability-list"><code>scene.open</code><code>scene.save</code><code>scene.entity.create</code><code>scene.entity.update</code><code>asset.import</code><code>runtime.play</code></div></aside>
    <main className="viewport-wrap"><div className="viewport-tabs"><button className={viewport === 'scene' ? 'active' : ''} onClick={() => setViewport('scene')}>Scene</button><button className={viewport === 'game' ? 'active' : ''} onClick={() => setViewport('game')}>Game</button><span className="viewport-label">{viewport === 'scene' ? '编辑器相机 · 正交' : running ? `FRAME ${frame} · ${paused ? 'PAUSED' : 'RUNNING'}` : '游戏视图 · 等待运行'}</span></div><div className="viewport"><div className={`viewport-grid ${viewport === 'game' ? 'game-mode' : ''}`} style={{ backgroundImage: grid && viewport === 'scene' ? 'linear-gradient(#172846 1px,transparent 1px),linear-gradient(90deg,#172846 1px,transparent 1px)' : 'none' }}><div className="scene-world"><span className="world-header">{scene.name} · {running ? 'PLAY MODE' : 'EDIT MODE'}</span>{activeEntities.map((e) => { const t = e.transform || {}; return <button key={e.id} className={`world-entity ${e.type.toLowerCase()} ${e.id === selectedId ? 'selected' : ''}`} style={{ left: `${Math.max(5, Math.min(95, 50 + Number(t.x || 0) * 4))}%`, top: `${Math.max(8, Math.min(92, 52 - Number(t.y || 0) * 6))}%`, display: e.visible === false ? 'none' : 'block' }} onClick={() => setSelectedId(e.id)}><span>{e.name}</span></button>; })}</div><span className="viewport-hud">{viewport === 'scene' ? 'WASD 移动相机 · 滚轮缩放' : running ? `FRAME ${frame} · ${paused ? 'PAUSED' : 'RUNNING'}` : '点击运行开始预览'}</span></div>{viewport === 'game' && !running && <div className="runtime-overlay"><div className="runtime-overlay-card"><h3>运行预览</h3><p>点击顶部“运行”启动 WebAssembly 场景</p></div></div>}</div></main>
    <aside className="editor-pane right"><div className="pane-heading"><span>Inspector</span><button onClick={() => selected && updateSelected({}, { x: 0, y: 0, rotation: 0, scale: 1 })}>↺</button></div>{selected ? <><section className="inspector-section"><h3>Entity</h3><label className="property"><span>Name</span><input disabled={running} value={selected.name} onChange={(e) => updateSelected({ name: e.target.value || 'Entity' })} /></label><label className="property"><span>Type</span><select disabled={running} value={selected.type} onChange={(e) => updateSelected({ type: e.target.value })}>{['Sprite', 'Camera', 'Light', 'Empty'].map((x) => <option key={x}>{x}</option>)}</select></label><label className="property"><span>Visible</span><input disabled={running} type="checkbox" checked={selected.visible !== false} onChange={(e) => updateSelected({ visible: e.target.checked })} /></label></section><section className="inspector-section"><div className="component-title"><b>Transform</b><button disabled={running} onClick={() => updateSelected({}, { x: 0, y: 0, rotation: 0, scale: 1 })}>Reset</button></div>{(['x', 'y', 'rotation', 'scale'] as const).map((key) => <label className="property" key={key}><span>{key === 'x' ? 'Position X' : key === 'y' ? 'Position Y' : key[0].toUpperCase() + key.slice(1)}</span><input disabled={running} type="number" step={key === 'scale' ? '.05' : '1'} value={Number(selected.transform?.[key] || (key === 'scale' ? 1 : 0))} onChange={(e) => updateSelected({}, { [key]: Number(e.target.value) || 0 })} /></label>)}</section><section className="inspector-section"><div className="component-title"><b>Components</b><button disabled={running} onClick={() => updateSelected({ components: [...new Set([...(selected.components || ['Transform']), 'Script'])] })}>＋</button></div>{(selected.components || ['Transform']).map((c) => <div className="muted" key={c}>▾ {c}</div>)}</section><section className="inspector-section" style={{ display: 'flex', gap: 7 }}><button disabled={running} style={{ flex: 1 }} onClick={duplicateEntity}>复制</button><button disabled={running} className="danger-button" style={{ flex: 1 }} onClick={deleteEntity}>删除</button></section></> : <div className="inspector-empty">从层级面板选择一个实体<br />查看和编辑组件属性</div>}</aside>
    <section className="editor-bottom"><div className="content-toolbar"><strong>Project</strong><span className="content-breadcrumb">Assets</span><span className="muted">{project.assets.length} 个资源</span><button className="tool-button" onClick={togglePause}>Ⅱ</button><button className="tool-button" onClick={stepRun}>▷|</button><input className="content-search" placeholder="搜索资源…" value={query} onChange={(e) => setQuery(e.target.value)} /><button className="tool-button" onClick={() => picker.current?.click()}>↥ 导入</button><input ref={picker} type="file" multiple hidden onChange={(e) => importAssets(e.target.files)} /></div><div className="content-grid">{filteredAssets.map((asset, i) => <button className="content-item" key={asset.id || `${asset.name}-${i}`}><span className={`file-icon ${asset.kind || 'file'}`}>{icon[asset.kind || 'file'] || '□'}</span><small>{asset.name}</small><span className="muted">{asset.type || asset.typeLabel || 'file'}</span></button>)}<button className="content-item import" onClick={() => picker.current?.click()}><span className="file-icon">＋</span><small>导入资源</small></button></div></section>
    <div className="toast-stack">{toasts.map((t) => <div className={`toast ${t.error ? 'error' : ''}`} key={t.id}><span>{t.error ? '!' : '✓'}</span><span>{t.text}</span><button onClick={() => setToasts((v) => v.filter((x) => x.id !== t.id))}>×</button></div>)}</div>
    {entityModal && <div className="modal open"><form className="dialog" onSubmit={(e) => { e.preventDefault(); addEntity(); }}><div className="dialog-head"><div><div className="eyebrow">Scene entity</div><h2>添加实体</h2></div><button type="button" onClick={() => setEntityModal(false)}>×</button></div><label className="field">名称<input required value={entityName} onChange={(e) => setEntityName(e.target.value)} placeholder="例如：Player" /></label><label className="field">类型<select value={entityType} onChange={(e) => setEntityType(e.target.value)}>{['Sprite', 'Camera', 'Light', 'Empty'].map((x) => <option key={x}>{x}</option>)}</select></label><div className="dialog-actions"><button type="button" onClick={() => setEntityModal(false)}>取消</button><button className="primary">添加实体</button></div></form></div>}
    {sceneModal && <div className="modal open"><form className="dialog" onSubmit={(e) => { e.preventDefault(); sceneModal === 'create' ? createScene() : renameScene(); }}><div className="dialog-head"><div><div className="eyebrow">Scene</div><h2>{sceneModal === 'create' ? '新建场景' : '重命名场景'}</h2></div><button type="button" onClick={() => setSceneModal(null)}>×</button></div><label className="field">场景名称<input required value={sceneName} onChange={(e) => setSceneName(e.target.value)} /></label><div className="dialog-actions"><button type="button" onClick={() => setSceneModal(null)}>取消</button><button className="primary">{sceneModal === 'create' ? '创建场景' : '保存名称'}</button></div></form></div>}
    {deleteScene && <div className="modal open"><div className="dialog"><div className="dialog-head"><h2>删除“{scene.name}”？</h2><button onClick={() => setDeleteScene(false)}>×</button></div><p className="dialog-subtitle">场景中的实体和未保存修改会被移除。</p><div className="dialog-actions"><button onClick={() => setDeleteScene(false)}>取消</button><button className="danger-button" onClick={removeScene}>删除场景</button></div></div></div>}
  </div>;
}
