#pragma once

// Browser/project persistence ABI.
//
// The engine uses ordinary std::filesystem paths.  On WebAssembly those
// paths point at Emscripten's virtual filesystem; callers mount the
// persistent IDBFS directory once and call tc_web_storage_sync() after a
// batch of writes.  The same API has a native implementation so the bridge
// can be unit-tested without a browser.

#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

// Mount an IDBFS-backed directory.  `mount_path` must be an absolute path
// (for example "/tomcat").  Calling this more than once with the same path
// is harmless.  Returns 0 on success and a negative value on failure.
int tc_web_storage_mount(const char* mount_path);

// Start an asynchronous IDBFS sync.  `populate` follows Emscripten's
// FS.syncfs convention: non-zero loads persisted data into the virtual file
// system, zero flushes virtual data to IndexedDB.  Completion is reported by
// tc_web_storage_sync_pending()/tc_web_storage_sync_last_ok() and by a
// `storage.sync` bridge event.  Returns 0 when the operation was scheduled.
int tc_web_storage_sync(int populate);
int tc_web_storage_sync_pending();
int tc_web_storage_sync_last_ok();

// Read the most recent storage error.  The pointer remains valid until the
// next storage call on the same thread and must not be freed by the caller.
const char* tc_web_storage_last_error();

int tc_web_storage_exists(const char* path);
int tc_web_storage_mkdir(const char* path);
int tc_web_storage_remove(const char* path);

// Binary file helpers.  tc_web_storage_read() returns the number of bytes
// copied, or a negative error code.  If the supplied buffer is too small it
// returns -2; use tc_web_storage_size() to obtain the required capacity.
int32_t tc_web_storage_size(const char* path);
int32_t tc_web_storage_read(const char* path, void* destination, uint32_t capacity);
int tc_web_storage_write(const char* path, const void* data, uint32_t size);

// Convenience text helpers for YAML project and scene files.  Read results
// are owned by the bridge and remain valid until the next read call on the
// same thread.
const char* tc_web_storage_read_text(const char* path);
int tc_web_storage_write_text(const char* path, const char* text);

// Return a JSON array describing the direct children of a directory.  Each
// item has `name`, `directory`, and (for regular files) `size` fields.  The
// returned string is owned by the bridge and remains valid until the next
// list/read call on the same thread.
const char* tc_web_storage_list(const char* directory);

// Project/scene convenience paths.  Project IDs are single ASCII slug
// segments (letters, digits, '.', '_' and '-').  Scene IDs are single file
// name segments: spaces, Unicode, and punctuation are allowed, while path
// separators, control characters, '.', and '..' are rejected.  Project files
// are stored at <mount>/projects/<project_id>/Project.tcproj and scenes at
// <mount>/projects/<project_id>/Assets/<scene_id>.tomcat.
int tc_web_project_create(const char* project_id, const char* name, const char* template_name);
int tc_web_project_save(const char* project_id, const char* yaml);
const char* tc_web_project_load(const char* project_id);
int tc_web_project_remove(const char* project_id);

int tc_web_scene_save(const char* project_id, const char* scene_id, const char* yaml);
const char* tc_web_scene_load(const char* project_id, const char* scene_id);
int tc_web_scene_remove(const char* project_id, const char* scene_id);

// Called by Emscripten's FS.syncfs callback.  It is exported for the small JS
// glue generated by tomcat_web_storage.cpp; applications should not call it
// directly.
void tc_web_storage_sync_complete(int populate, int ok);

#ifdef __cplusplus
}
#endif
