[build]
publish = "dist"

[[headers]]
  for = "/runtime/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
